set -x
ENGINE=${1:-vllm}
HF_ENDPOINT="https://hf-mirror.com"
PROJECT_DIR="/home/renxinlin/spectrack"
export CUDA_VISIBLE_DEVICES=4,5,6,7
# If you are using vllm<=0.6.3, you might need to set the following environment variable to avoid bugs:
# export VLLM_ATTENTION_BACKEND=XFORMERS

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=$PROJECT_DIR/spec1k/dataset/rlhf/train.parquet \
    data.val_files=$PROJECT_DIR/spec1k/dataset/rlhf/test.parquet \
    data.train_batch_size=16\
    data.max_prompt_length=1024\
    data.max_response_length=512\
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    data.image_key=images \
    custom_reward_function.path=$PROJECT_DIR/spec1k/reward/custom_reward.py \
    custom_reward_function.name=compute_score \
    actor_rollout_ref.model.path=Qwen/Qwen2.5-VL-32B-Instruct \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.lora_rank=64 \
    actor_rollout_ref.model.lora_alpha=32 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=16\
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1\
    actor_rollout_ref.actor.use_kl_loss=False\
    actor_rollout_ref.actor.kl_loss_coef=0 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=True\
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True\
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1\
    actor_rollout_ref.rollout.tensor_model_parallel_size=4 \
    actor_rollout_ref.rollout.name=$ENGINE \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.9 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=True \
    actor_rollout_ref.rollout.n=4 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1\
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger='["tensorboard"]' \
    trainer.project_name='specktrack' \
    trainer.nnodes=1 \
    trainer.save_freq=20000\
    trainer.test_freq=20000 \
    trainer.total_epochs=15 $@
